### ISSUE TITLE
Doesn't work with HASS 0.89.1

### ISSUE THREAD

**Issue by danielkucera** [Hy3n4/ha-cc-cometblue#4]
**Describe the bug**
It doesn't work with HASS 0.89.1

**To Reproduce**
1. Upgrade to HASS to 0.89.1
2. Start it
3. See error in ~/.homeassistant/home-assistant.log

**Expected behavior**
I'd like it to work

**Version of component**
- Version 881216b134bb3611cda4d925dcc25fc4bc1de6bf

**Homeassistant (please complete the following information):**
 - Browser Firefox
 - Version 0.89.1

**Error message**
```
2019-03-08 10:49:10 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.climate.cometblue. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/opt/hass/lib/python3.5/site-packages/homeassistant/loader.py", line 166, in _load_file
    module = importlib.import_module(path)
  File "/opt/hass/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/root/.homeassistant/custom_components/climate/cometblue.py", line 16, in <module>
    from homeassistant.components.climate import (
ImportError: cannot import name 'STATE_AUTO'
2019-03-08 10:49:10 ERROR (MainThread) [homeassistant.loader] Unable to find platform cometblue.
```
